@echo off
cls
mode 140,41
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO#########OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO#
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO##o°      .OOOOOOOOOOOOOOOOOOOOOOOOOO######OOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO##°        .oOOOOOOOOOOOOOOOOOOOOOOOOO     °o##OOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO#o      .o####OOOOOOOOOOOOOOOOOOOOOOOOOo       .OOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO#°     *###OOOOOOOOOOOOOOOOOOOOOOOOOOOOO##*      °#OOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO#°    o###OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO#*      #OOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO######OOOOOOOoO.   .OOoooooOOOOOOOO#######OOOOOOOOOOOOOOOOO#.     #OOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOO##OOOoooo********ooo**o  °oooooooo*********ooooOOOO####OOOOOOOOOO#     #OOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOO#o****ooOOOO##########@° *@##############OOOOooo*****oooOO####OOOO#.    #OOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOO#O°°O##################O#°*##########################OOOoo**°**oOO###o    #OOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOO#o.o########################################################O***°°°°*oo    #OOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOO#*.O####################o O###################################ooooo***°°   .#OOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOO#°.#####################O  ####################################o*****oooooo .#OOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOO#°.######################  @####################################o*o********o* #OOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOO#* ##############################################################O**********o..#OOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOO O#####################O *######################################O*o*******o° OOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOO#.*######################  ###############OOOooooooooOOO##########O*o*****oo..#OOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOO#OOo* ooooooooooooO#########O o###########OooooO###@@@@@##OooooO######O*o****o* *#OOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOO##O**oO#@@@@@@@@@@@#Oo**o#######@##########o*oO@@@@@@@@@@@@@@@@@@Oo*o####O*o***o* o#OOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOO#O°*#@@@@@@@@@@@@@@@@@@@@o*o###O o########O°o@@@@@@@@@@@@@@@@@@@@@@@@o°O##o*o**o*.o#OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOO#*°#@@@@@@@@@@@@@@@@@@@@@@@@o.#@  o#######o.@@@@@@@@@@@@@@@@@@@@@@@@@@@@.o#o***o*°O#OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOO#*.@@@@OO@@@@@@@@@@@@@@@@@@@@@O.@  ######## @@@@@@@@@@@@@@@@@o  @@@@@@@@@@ Oo**o*°O#OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOO# #@@@o  O@@@@@@@@@@@@@@@@@@@@@.o#########o.@@@@@@@@@@@@@@@@@o .@@@@@@@@@@°*o*o*.O#OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOO# #@@@@@@@@@@@@@@@@@@@@@@@@@@@@.*  #######O @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.*o*o o#OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOO#*.@@@@@@@@@@@@@@@@@@@@@@@@@@@O.O  @#######°°@@@@@@@@@@@@@@@@@@@@@@@@@@@@*°o*o *#OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOO#*°#@@@@@@@@@@@@@@@@@@@@@@@@o.#O .#########*°#@@@@@@@@@@@@@@@@@@@@@@@@#°*O*o..#OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOO#o°*#@@@@@@@@@@@@@@@@@@@@O**###oO##########O**O@@@@@@@@@@@@@@@@@@@@O**O#*o* #OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOO##o**oO#@@@@@@@@@@@@#Oo*o#####  ############Oo*oO#@@@@@@@@@@@@#Oo*oO##o*o o#OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOO##OOoooo*.OooooooooO#######.     o############OooooooooooooooOO####o*o°.#OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOO###OO..##O#############O* .OoO################################o**o o#OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOO#°.#################°*@################################Oo**o° #OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOO#o.oOOOOOoooooooooo* °OooOOOOOO##O##################Oo**o*o *#OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOO#O**oooooooooooooooooooo     .  o******oo*ooOOO#OOo**oo*** OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOO###################O#* ..  .. o#OOOOO* °*o°  o*******oo° #OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO   .  ..  #OO#*°*##O#.° O*o*oooo°° .#OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO#. .  ..    o#o *o...oO O #o*o**.     #OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoOO#* .°  * °# OO*o*        #OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO##°  OO O* °# O#o*o°       °#OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO#*   °@o o *OO O#Oo*o°       °#OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO#°    ##o O* *# o##o**o*       OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO#o   .##o O..o# *##O*o*oo*    .####OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO### *##o # .°# °##O*o***o* @Oo°.   °OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO# O##O.**. **O##O*o****o     °*oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO #@############O*oooooO  O#####OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO*  °oOOOOOOOO#O*o***°°°°°#OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO@       o******°       #OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO#o      #O###O#O      °#OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO####.     OOOOOOO#.     oOOOOOOOOOOOOOOOOOOOOOO#########OOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoo***     .°°°....°     ...................°°°°°°°****ooOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO*°°....            .   .                       ......°°*OOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO###OOOOOOOoooooooo**ooo***************ooooooooOOOOOOO###OOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO####################################OOOOOOOOOOOOOOOOOOOOO
echo OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO#

echo A BAD ROBOT PRODUCTION !!
echo PREMINGING TESTING V.02
timeout 10
python ./PREMINER.py
pause